package miproyecto.appticorentcar.capaGrafica;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import miproyecto.appticorentcar.capalogica.Agencia;
import miproyecto.appticorentcar.capalogica.Auto;
import miproyecto.appticorentcar.capalogica.Alquiler;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Isaac Serrano, cedula 208330122
 */
public class FrmAlquilerAuto extends javax.swing.JFrame {

    private String tipoSeleccionado;
    private String marcaSeleccionada;
    private int anioMin;
    private int anioMax;
    private Agencia agencia;

    /**
     * Creates new form FrmAlquilerAuto
     */
    public FrmAlquilerAuto(Agencia agencia) {
        this.agencia = agencia;
        setContentPane(new PanelConFondo("/imagenes/autospr.jpg"));
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOpcion = new javax.swing.JLabel();
        btnDefinirCaracteristicasdeAuto = new javax.swing.JButton();
        btnBuscarAutoDisponible = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOpcion.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblOpcion.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion.setText("Opciones :");

        btnDefinirCaracteristicasdeAuto.setBackground(new java.awt.Color(51, 102, 255));
        btnDefinirCaracteristicasdeAuto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnDefinirCaracteristicasdeAuto.setForeground(new java.awt.Color(255, 255, 255));
        btnDefinirCaracteristicasdeAuto.setText("Definir Caracteristicas de Autos");
        btnDefinirCaracteristicasdeAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirCaracteristicasdeAutoActionPerformed(evt);
            }
        });

        btnBuscarAutoDisponible.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarAutoDisponible.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscarAutoDisponible.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarAutoDisponible.setText("Buscar Auto Disponible");
        btnBuscarAutoDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAutoDisponibleActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Alquiler de Auto");

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver al Menu Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(lblOpcion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(btnBuscarAutoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnDefinirCaracteristicasdeAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblOpcion)
                .addGap(18, 18, 18)
                .addComponent(btnDefinirCaracteristicasdeAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAutoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDefinirCaracteristicasdeAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirCaracteristicasdeAutoActionPerformed
        try {
            String tipo = (String) JOptionPane.showInputDialog(this,
                    "Seleccione el tipo de auto:",
                    "Tipo de Auto",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new String[]{"Automovil", "Doble Traccion"},
                    "Automovil");

            String marca = JOptionPane.showInputDialog("Ingresa la marca deseada:");
            int anioMin = Integer.parseInt(JOptionPane.showInputDialog("Año mínimo:"));
            int anioMax = Integer.parseInt(JOptionPane.showInputDialog("Año máximo:"));

            // GUARDAR en variables globales
            tipoSeleccionado = tipo;
            marcaSeleccionada = marca;
            this.anioMin = anioMin;
            this.anioMax = anioMax;

            jTextArea1.setText("""
                            Características Seleccionadas:
                            Tipo: %s
                            Marca: %s
                            Año entre: %d - %d
                            """.formatted(tipo, marca, anioMin, anioMax));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Entrada inválida. Intentar de nuevo.");
        }


    }//GEN-LAST:event_btnDefinirCaracteristicasdeAutoActionPerformed

    private void btnBuscarAutoDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutoDisponibleActionPerformed

        if (tipoSeleccionado == null || marcaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Primero defina las características del auto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Auto[] autos = agencia.getAutos();
        boolean encontrado = false;

        for (Auto auto : autos) {
            if (auto.isEstado()
                    && auto.getTipoAuto().equalsIgnoreCase(tipoSeleccionado)
                    && auto.getMarca().toLowerCase().contains(marcaSeleccionada.toLowerCase())
                    && auto.getModelo() >= anioMin && auto.getModelo() <= anioMax) {

                jTextArea1.setText("Auto encontrado:\n" + auto.toString());

                int opcion = JOptionPane.showConfirmDialog(this, "¿Desea alquilar este auto?", "Confirmar alquiler", JOptionPane.YES_NO_OPTION);

                if (opcion == JOptionPane.YES_OPTION) {
                    LocalDate hoy = LocalDate.now();
                    int diaAlq = hoy.getDayOfMonth();
                    int mesAlq = hoy.getMonthValue();
                    int annoAlq = hoy.getYear();

                    int diaDev = Integer.parseInt(JOptionPane.showInputDialog("Día de devolución esperada:"));
                    int mesDev = Integer.parseInt(JOptionPane.showInputDialog("Mes de devolución esperada:"));
                    int annoDev = Integer.parseInt(JOptionPane.showInputDialog("Año de devolución esperada:"));

                    int diasAlquiler = agencia.calcularDiasEntreFechas(diaAlq, mesAlq, annoAlq, diaDev, mesDev, annoDev);

                    if (diasAlquiler < 0) {
                        JOptionPane.showMessageDialog(this, "La fecha de devolución no puede ser anterior a la fecha de alquiler.", "Error de Fecha", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    boolean seguroTerceros = JOptionPane.showConfirmDialog(this,
                            "¿Desea seguro a terceros? ($25 por día)", "Seguro Opcional", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;

                    double montoSeguroObligatorio;
                    int modelo = auto.getModelo();

                    if (auto.getTipoAuto().equalsIgnoreCase("Automovil")) {
                        if (modelo < 1990) {
                            montoSeguroObligatorio = 5000;
                        } else if (modelo <= 1995) {
                            montoSeguroObligatorio = 10000;
                        } else if (modelo <= 2000) {
                            montoSeguroObligatorio = 15000;
                        } else {
                            montoSeguroObligatorio = 20000;
                        }
                    } else {
                        if (modelo < 1990) {
                            montoSeguroObligatorio = 20000;
                        } else if (modelo <= 1995) {
                            montoSeguroObligatorio = 25000;
                        } else if (modelo <= 2000) {
                            montoSeguroObligatorio = 30000;
                        } else {
                            montoSeguroObligatorio = 25000;
                        }
                    }

                    double montoSeguroTerceros = seguroTerceros ? diasAlquiler * 25 : 0;

                    String nombreCliente = JOptionPane.showInputDialog("Nombre del cliente:");
                    String cedulaCliente = JOptionPane.showInputDialog("Cédula del cliente:");
                    String[] tipos = {"Regular", "Corporativo"};
                    int tipoCliente = JOptionPane.showOptionDialog(this, "Seleccione el tipo de cliente:",
                            "Tipo de Cliente",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            tipos,
                            tipos[0]);

                    if (tipoCliente == -1) {
                        JOptionPane.showMessageDialog(this, "No seleccionó un tipo de cliente.");
                        return;
                    }

                    auto.setNombreCliente(nombreCliente);
                    auto.setCedulaCliente(cedulaCliente);
                    auto.setTipoCliente(tipoCliente == 0 ? Auto.CLIENTE_REGULAR : Auto.CLIENTE_CORPORATIVO);

                    Alquiler nuevoAlquiler = new Alquiler(
                            auto.getPlaca(),
                            diaAlq, mesAlq, annoAlq,
                            diaDev, mesDev, annoDev,
                            0, 0, 0,
                            montoSeguroObligatorio,
                            montoSeguroTerceros,
                            auto.getKilometraje(),
                            0,
                            true
                    );

                    int indiceAuto = agencia.obtenerIndiceAuto(auto.getPlaca());
                    agencia.agregarAlquiler(indiceAuto, nuevoAlquiler);
                    auto.setEstado(false);

                    jTextArea1.setText("¡Alquiler registrado exitosamente!\n\n" + nuevoAlquiler.toString());
                }

                encontrado = true;
                break;
            }

        }

        if (!encontrado) {
            jTextArea1.setText("No se encontró ningún auto disponible con esas características.");
        }

    }//GEN-LAST:event_btnBuscarAutoDisponibleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FrmVentanaMenuPrincipal menu = new FrmVentanaMenuPrincipal(agencia);
        menu.setVisible(true);
        dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmAlquilerAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmAlquilerAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmAlquilerAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmAlquilerAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAutoDisponible;
    private javax.swing.JButton btnDefinirCaracteristicasdeAuto;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblOpcion;
    // End of variables declaration//GEN-END:variables
}
