/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miproyecto.appticorentcar.capaGrafica;

import javax.swing.JOptionPane;
import miproyecto.appticorentcar.capalogica.Agencia;
import miproyecto.appticorentcar.capalogica.Alquiler;
import miproyecto.appticorentcar.capalogica.Auto;

/**
 *
 * @author Isaac Serrano, cedula 208330122
 */
public class FrmDevolucionAuto extends javax.swing.JFrame {

    private Agencia agencia;

    /**
     * Creates new form FrmDevolucionAuto
     */
    public FrmDevolucionAuto(Agencia agencia) {
        this.agencia = agencia;
        setContentPane(new PanelConFondo("/imagenes/Devpor.png"));

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnRegistrarDevolucion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Devolucion de Auto");

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnRegistrarDevolucion.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistrarDevolucion.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRegistrarDevolucion.setText("Registrar Devolucion ");
        btnRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDevolucionActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSalir.setText("Finalizar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(0, 102, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnVolver.setText("Volver al Menu Anterior");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(btnRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucionActionPerformed
        String placa = JOptionPane.showInputDialog(this, "Ingrese la placa del Auto:");
        int indice = agencia.buscarAutoPorPlaca(placa);

        if (indice == -1) {
            JOptionPane.showMessageDialog(this, "Auto no Encontrado");
            return;
        }

        Auto auto = agencia.getAutos()[indice];

        if (auto.isEstado()) {
            JOptionPane.showMessageDialog(this, "Este Auto ya está Libre");
            return;
        }

        Alquiler alquiler = agencia.buscarAlquilerPendiente(placa);
        if (alquiler == null) {
            JOptionPane.showMessageDialog(this, "No hay alquiler pendiente para este Auto");
            return;
        }

        try {
            int dia = Integer.parseInt(JOptionPane.showInputDialog("Día de la Devolución:"));
            int mes = Integer.parseInt(JOptionPane.showInputDialog("Mes de la Devolución:"));
            int anno = Integer.parseInt(JOptionPane.showInputDialog("Año de la Devolución:"));

            int kmFinal = Integer.parseInt(JOptionPane.showInputDialog("Kilometraje Actual del Auto:"));

            // Valida que el kilometraje final no sea menor que el inicial
            if (kmFinal < alquiler.getKmInicial()) {
                JOptionPane.showMessageDialog(this, "Error: El kilometraje final no puede ser menor que el inicial.");
                return;
            }

            // Valida que no haya una diferencia de kilómetros demasiado grande
            int kmRecorridos = kmFinal - alquiler.getKmInicial();
            if (kmRecorridos > 5000) {
                int confirmar = JOptionPane.showConfirmDialog(this,
                        "El vehículo recorrió más de 5000 km. ¿Desea continuar?",
                        "Confirmar Kilometraje", JOptionPane.YES_NO_OPTION);
                if (confirmar != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            int diasReales = agencia.calcularDiasEntreFechas(
                    alquiler.getDiaAlquiler(), alquiler.getMesAlquiler(), alquiler.getAnnioAlquiler(),
                    dia, mes, anno);

            double montoDias = diasReales * 1000;
            double montoKm = kmRecorridos * 100;

            alquiler.setDiaDevolucionReal(dia);
            alquiler.setMesDevolucionReal(mes);
            alquiler.setAnnioDevolucionReal(anno);
            alquiler.setKmFinal(kmFinal);
            alquiler.setMontoPorDias(montoDias);
            alquiler.setMontoPorKilometraje(montoKm);
            alquiler.setPendiente(false);

            agencia.liberarAuto(placa);

            String resumen = String.format("""
                Auto devuelto exitosamente.
                        
                        Placa: %s
                        Fecha de Alquiler: %02d/%02d/%d
                        Fecha de Devolución Real: %02d/%02d/%d
                        Kilometraje Inicial: %,d km
                        Kilometraje Final: %,d km
                        
                        --- Cargos ---
                        Seguro Obligatorio: ₡%,.2f
                        Seguro a Terceros: ₡%,.2f
                        Monto por Días: ₡%,.2f
                        Monto por Kilometraje: ₡%,.2f
                        
                        Monto Total a Pagar: ₡%,.2f
                """,
                    alquiler.getPlaca(),
                    alquiler.getDiaAlquiler(), alquiler.getMesAlquiler(), alquiler.getAnnioAlquiler(),
                    alquiler.getDiaDevolucionReal(), alquiler.getMesDevolucionReal(), alquiler.getAnnioDevolucionReal(),
                    alquiler.getKmInicial(),
                    alquiler.getKmFinal(),
                    alquiler.getMontoSeguroObligatorio(),
                    alquiler.getMontoSeguroTerceros(),
                    alquiler.getMontoPorDias(),
                    alquiler.getMontoPorKilometraje(),
                    alquiler.getMontoTotal()
            );

            txtResultado.setText(resumen);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos inválidos. Verifique los valores ingresados.");
        }


    }//GEN-LAST:event_btnRegistrarDevolucionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmVentanaMenuPrincipal menu = new FrmVentanaMenuPrincipal(agencia);
        menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmDevolucionAuto().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDevolucion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
